import mock from '../mock'; // Asegúrate de que la ruta sea correcta

import { managementVulnerabilityType } from 'src/types/vulnerabilities/vulnerabilityManagementType';

let managementVuln: managementVulnerabilityType[] = [
  {
    id: 1,
    vulnerability_id: 'CVE-2021-24171',
    type: 'CRITICAL',
    severity: 9.8,
    name: 'CVE-2021-24171 woocommerce',
    creation_time: '2024-10-29T21:38:35.924805Z',
    qod: '0',
    hosts: 'https://prueba-tu-pala.ofertasdepadel.com/',
    port: '443',
    tool: 'WordPress',
    description: '',
    report_id: 'q4Q32pIBHPjIIpHRgipU',
    report_date: '2024-10-29T21:38:35.924805Z',
    responsible: null,
    role: null,
    notes: null,
    work_plan: null,
    compensatory_controls: null,
    recategorization: null,
    estimated_budget: null,
    last_revision_date: '2024-10-29T21:39:08.154256Z',
    estimated_closure_date: null,
    closure_date: null,
    closure_reason: null,
    status: 'OPEN',
    evidence: null,
  },
  {
    id: 2,
    vulnerability_id: 'CVE-2023-52222',
    type: 'HIGH',
    severity: 8.8,
    name: 'CVE-2023-52222 woocommerce',
    creation_time: '2024-10-29T21:38:35.924805Z',
    qod: '0',
    hosts: 'https://prueba-tu-pala.ofertasdepadel.com/',
    port: '443',
    tool: 'WordPress',
    description: '',
    report_id: 'q4Q32pIBHPjIIpHRgipU',
    report_date: '2024-10-29T21:38:35.924805Z',
    responsible: null,
    role: null,
    notes: null,
    work_plan: null,
    compensatory_controls: null,
    recategorization: null,
    estimated_budget: null,
    last_revision_date: '2024-10-29T21:39:08.154328Z',
    estimated_closure_date: null,
    closure_date: null,
    closure_reason: null,
    status: 'OPEN',
    evidence: null,
  },
  {
    id: 3,
    vulnerability_id: 'CVE-2024-9944',
    type: 'MEDIUM',
    severity: 6.1,
    name: 'CVE-2024-9944 woocommerce',
    creation_time: '2024-10-29T21:38:35.924805Z',
    qod: '0',
    hosts: 'https://prueba-tu-pala.ofertasdepadel.com/',
    port: '443',
    tool: 'WordPress',
    description: '',
    report_id: 'q4Q32pIBHPjIIpHRgipU',
    report_date: '2024-10-29T21:38:35.924805Z',
    responsible: null,
    role: null,
    notes: null,
    work_plan: null,
    compensatory_controls: null,
    recategorization: null,
    estimated_budget: null,
    last_revision_date: '2024-10-29T21:39:08.154369Z',
    estimated_closure_date: null,
    closure_date: null,
    closure_reason: null,
    status: 'OPEN',
    evidence: null,
  },
  {
    id: 4,
    vulnerability_id: 'CVE-2023-32801',
    type: 'MEDIUM',
    severity: 6.1,
    name: 'CVE-2023-32801 woocommerce',
    creation_time: '2024-10-29T21:38:35.924805Z',
    qod: '0',
    hosts: 'https://prueba-tu-pala.ofertasdepadel.com/',
    port: '443',
    tool: 'WordPress',
    description: '',
    report_id: 'q4Q32pIBHPjIIpHRgipU',
    report_date: '2024-10-29T21:38:35.924805Z',
    responsible: null,
    role: null,
    notes: null,
    work_plan: null,
    compensatory_controls: null,
    recategorization: null,
    estimated_budget: null,
    last_revision_date: '2024-10-29T21:39:08.154405Z',
    estimated_closure_date: null,
    closure_date: null,
    closure_reason: null,
    status: 'OPEN',
    evidence: null,
  },
  {
    id: 5,
    vulnerability_id: 'CVE-2024-35656',
    type: 'MEDIUM',
    severity: 6.1,
    name: 'CVE-2024-35656 elementor',
    creation_time: '2024-10-29T21:38:35.924805Z',
    qod: '0',
    hosts: 'https://prueba-tu-pala.ofertasdepadel.com/',
    port: '443',
    tool: 'WordPress',
    description: '',
    report_id: 'q4Q32pIBHPjIIpHRgipU',
    report_date: '2024-10-29T21:38:35.924805Z',
    responsible: null,
    role: null,
    notes: null,
    work_plan: null,
    compensatory_controls: null,
    recategorization: null,
    estimated_budget: null,
    last_revision_date: '2024-10-29T21:39:08.154438Z',
    estimated_closure_date: null,
    closure_date: null,
    closure_reason: null,
    status: 'OPEN',
    evidence: null,
  },
  {
    id: 6,
    vulnerability_id: 'CVE-2024-37297',
    type: 'MEDIUM',
    severity: 5.4,
    name: 'CVE-2024-37297 woocommerce',
    creation_time: '2024-10-29T21:38:35.924805Z',
    qod: '0',
    hosts: 'https://prueba-tu-pala.ofertasdepadel.com/',
    port: '443',
    tool: 'WordPress',
    description: '',
    report_id: 'q4Q32pIBHPjIIpHRgipU',
    report_date: '2024-10-29T21:38:35.924805Z',
    responsible: null,
    role: null,
    notes: null,
    work_plan: null,
    compensatory_controls: null,
    recategorization: null,
    estimated_budget: null,
    last_revision_date: '2024-10-29T21:39:08.154472Z',
    estimated_closure_date: null,
    closure_date: null,
    closure_reason: null,
    status: 'OPEN',
    evidence: null,
  },
  {
    id: 7,
    vulnerability_id: 'CVE-2024-5416',
    type: 'MEDIUM',
    severity: 5.4,
    name: 'CVE-2024-5416 elementor',
    creation_time: '2024-10-29T21:38:35.924805Z',
    qod: '0',
    hosts: 'https://prueba-tu-pala.ofertasdepadel.com/',
    port: '443',
    tool: 'WordPress',
    description: '',
    report_id: 'q4Q32pIBHPjIIpHRgipU',
    report_date: '2024-10-29T21:38:35.924805Z',
    responsible: null,
    role: null,
    notes: null,
    work_plan: null,
    compensatory_controls: null,
    recategorization: null,
    estimated_budget: null,
    last_revision_date: '2024-10-29T21:39:08.154503Z',
    estimated_closure_date: null,
    closure_date: null,
    closure_reason: null,
    status: 'OPEN',
    evidence: null,
  },
  {
    id: 8,
    vulnerability_id: 'CVE-2024-37437',
    type: 'MEDIUM',
    severity: 5.4,
    name: 'CVE-2024-37437 elementor',
    creation_time: '2024-10-29T21:38:35.924805Z',
    qod: '0',
    hosts: 'https://prueba-tu-pala.ofertasdepadel.com/',
    port: '443',
    tool: 'WordPress',
    description: '',
    report_id: 'q4Q32pIBHPjIIpHRgipU',
    report_date: '2024-10-29T21:38:35.924805Z',
    responsible: null,
    role: null,
    notes: null,
    work_plan: null,
    compensatory_controls: null,
    recategorization: null,
    estimated_budget: null,
    last_revision_date: '2024-10-29T21:39:08.154535Z',
    estimated_closure_date: null,
    closure_date: null,
    closure_reason: null,
    status: 'OPEN',
    evidence: null,
  },
  {
    id: 9,
    vulnerability_id: 'CVE-2024-6757',
    type: 'MEDIUM',
    severity: 4.3,
    name: 'CVE-2024-6757 elementor',
    creation_time: '2024-10-29T21:38:35.924805Z',
    qod: '0',
    hosts: 'https://prueba-tu-pala.ofertasdepadel.com/',
    port: '443',
    tool: 'WordPress',
    description: '',
    report_id: 'q4Q32pIBHPjIIpHRgipU',
    report_date: '2024-10-29T21:38:35.924805Z',
    responsible: null,
    role: null,
    notes: null,
    work_plan: null,
    compensatory_controls: null,
    recategorization: null,
    estimated_budget: null,
    last_revision_date: '2024-10-29T21:39:08.154567Z',
    estimated_closure_date: null,
    closure_date: null,
    closure_reason: null,
    status: 'OPEN',
    evidence: null,
  },
  {
    id: 10,
    vulnerability_id: 'wp-super-cache',
    type: 'LOW',
    severity: 3.0,
    name: 'wp-super-cache',
    creation_time: '2024-10-29T21:38:35.924805Z',
    qod: '0',
    hosts: 'https://prueba-tu-pala.ofertasdepadel.com/',
    port: '443',
    tool: 'WordPress',
    description: '',
    report_id: 'q4Q32pIBHPjIIpHRgipU',
    report_date: '2024-10-29T21:38:35.924805Z',
    responsible: null,
    role: null,
    notes: null,
    work_plan: null,
    compensatory_controls: null,
    recategorization: null,
    estimated_budget: null,
    last_revision_date: '2024-10-29T21:39:08.154599Z',
    estimated_closure_date: null,
    closure_date: null,
    closure_reason: null,
    status: 'OPEN',
    evidence: null,
  },
  {
    id: 11,
    vulnerability_id: 'wordpress-seo',
    type: 'LOW',
    severity: 3.0,
    name: 'wordpress-seo',
    creation_time: '2024-10-29T21:38:35.924805Z',
    qod: '0',
    hosts: 'https://prueba-tu-pala.ofertasdepadel.com/',
    port: '443',
    tool: 'WordPress',
    description: '',
    report_id: 'q4Q32pIBHPjIIpHRgipU',
    report_date: '2024-10-29T21:38:35.924805Z',
    responsible: null,
    role: null,
    notes: null,
    work_plan: null,
    compensatory_controls: null,
    recategorization: null,
    estimated_budget: null,
    last_revision_date: '2024-10-29T21:39:08.154630Z',
    estimated_closure_date: null,
    closure_date: null,
    closure_reason: null,
    status: 'OPEN',
    evidence: null,
  },
  {
    id: 12,
    vulnerability_id: 'woocommerce-google-analytics-integration',
    type: 'LOW',
    severity: 3.0,
    name: 'woocommerce-google-analytics-integration',
    creation_time: '2024-10-29T21:38:35.924805Z',
    qod: '0',
    hosts: 'https://prueba-tu-pala.ofertasdepadel.com/',
    port: '443',
    tool: 'WordPress',
    description: '',
    report_id: 'q4Q32pIBHPjIIpHRgipU',
    report_date: '2024-10-29T21:38:35.924805Z',
    responsible: null,
    role: null,
    notes: null,
    work_plan: null,
    compensatory_controls: null,
    recategorization: null,
    estimated_budget: null,
    last_revision_date: '2024-10-29T21:39:08.154661Z',
    estimated_closure_date: null,
    closure_date: null,
    closure_reason: null,
    status: 'OPEN',
    evidence: null,
  },
  {
    id: 13,
    vulnerability_id: 'woocommerce',
    type: 'LOW',
    severity: 3.0,
    name: 'woocommerce',
    creation_time: '2024-10-29T21:38:35.924805Z',
    qod: '0',
    hosts: 'https://prueba-tu-pala.ofertasdepadel.com/',
    port: '443',
    tool: 'WordPress',
    description: '',
    report_id: 'q4Q32pIBHPjIIpHRgipU',
    report_date: '2024-10-29T21:38:35.924805Z',
    responsible: null,
    role: null,
    notes: null,
    work_plan: null,
    compensatory_controls: null,
    recategorization: null,
    estimated_budget: null,
    last_revision_date: '2024-10-29T21:39:08.154691Z',
    estimated_closure_date: null,
    closure_date: null,
    closure_reason: null,
    status: 'OPEN',
    evidence: null,
  },
  {
    id: 14,
    vulnerability_id: 'woo-variation-swatches',
    type: 'LOW',
    severity: 3.0,
    name: 'woo-variation-swatches',
    creation_time: '2024-10-29T21:38:35.924805Z',
    qod: '0',
    hosts: 'https://prueba-tu-pala.ofertasdepadel.com/',
    port: '443',
    tool: 'WordPress',
    description: '',
    report_id: 'q4Q32pIBHPjIIpHRgipU',
    report_date: '2024-10-29T21:38:35.924805Z',
    responsible: null,
    role: null,
    notes: null,
    work_plan: null,
    compensatory_controls: null,
    recategorization: null,
    estimated_budget: null,
    last_revision_date: '2024-10-29T21:39:08.154721Z',
    estimated_closure_date: null,
    closure_date: null,
    closure_reason: null,
    status: 'OPEN',
    evidence: null,
  },
  {
    id: 15,
    vulnerability_id: 'tp-product-image-flipper-for-woocommerce',
    type: 'LOW',
    severity: 3.0,
    name: 'tp-product-image-flipper-for-woocommerce',
    creation_time: '2024-10-29T21:38:35.924805Z',
    qod: '0',
    hosts: 'https://prueba-tu-pala.ofertasdepadel.com/',
    port: '443',
    tool: 'WordPress',
    description: '',
    report_id: 'q4Q32pIBHPjIIpHRgipU',
    report_date: '2024-10-29T21:38:35.924805Z',
    responsible: null,
    role: null,
    notes: null,
    work_plan: null,
    compensatory_controls: null,
    recategorization: null,
    estimated_budget: null,
    last_revision_date: '2024-10-29T21:39:08.154751Z',
    estimated_closure_date: null,
    closure_date: null,
    closure_reason: null,
    status: 'OPEN',
    evidence: null,
  },
  {
    id: 16,
    vulnerability_id: 'elementor',
    type: 'LOW',
    severity: 3.0,
    name: 'elementor',
    creation_time: '2024-10-29T21:38:35.924805Z',
    qod: '0',
    hosts: 'https://prueba-tu-pala.ofertasdepadel.com/',
    port: '443',
    tool: 'WordPress',
    description: '',
    report_id: 'q4Q32pIBHPjIIpHRgipU',
    report_date: '2024-10-29T21:38:35.924805Z',
    responsible: null,
    role: null,
    notes: null,
    work_plan: null,
    compensatory_controls: null,
    recategorization: null,
    estimated_budget: null,
    last_revision_date: '2024-10-29T21:39:08.154781Z',
    estimated_closure_date: null,
    closure_date: null,
    closure_reason: null,
    status: 'OPEN',
    evidence: null,
  },
  {
    id: 17,
    vulnerability_id: 'creame-whatsapp-me',
    type: 'LOW',
    severity: 3.0,
    name: 'creame-whatsapp-me',
    creation_time: '2024-10-29T21:38:35.924805Z',
    qod: '0',
    hosts: 'https://prueba-tu-pala.ofertasdepadel.com/',
    port: '443',
    tool: 'WordPress',
    description: '',
    report_id: 'q4Q32pIBHPjIIpHRgipU',
    report_date: '2024-10-29T21:38:35.924805Z',
    responsible: null,
    role: null,
    notes: null,
    work_plan: null,
    compensatory_controls: null,
    recategorization: null,
    estimated_budget: null,
    last_revision_date: '2024-10-29T21:39:08.154811Z',
    estimated_closure_date: null,
    closure_date: null,
    closure_reason: null,
    status: 'OPEN',
    evidence: null,
  },
  {
    id: 18,
    vulnerability_id: 'cookie-law-info',
    type: 'LOW',
    severity: 3.0,
    name: 'cookie-law-info',
    creation_time: '2024-10-29T21:38:35.924805Z',
    qod: '0',
    hosts: 'https://prueba-tu-pala.ofertasdepadel.com/',
    port: '443',
    tool: 'WordPress',
    description: '',
    report_id: 'q4Q32pIBHPjIIpHRgipU',
    report_date: '2024-10-29T21:38:35.924805Z',
    responsible: null,
    role: null,
    notes: null,
    work_plan: null,
    compensatory_controls: null,
    recategorization: null,
    estimated_budget: null,
    last_revision_date: '2024-10-29T21:39:08.154847Z',
    estimated_closure_date: null,
    closure_date: null,
    closure_reason: null,
    status: 'OPEN',
    evidence: null,
  },
  {
    id: 19,
    vulnerability_id: 'contact-form-7',
    type: 'LOW',
    severity: 3.0,
    name: 'contact-form-7',
    creation_time: '2024-10-29T21:38:35.924805Z',
    qod: '0',
    hosts: 'https://prueba-tu-pala.ofertasdepadel.com/',
    port: '443',
    tool: 'WordPress',
    description: '',
    report_id: 'q4Q32pIBHPjIIpHRgipU',
    report_date: '2024-10-29T21:38:35.924805Z',
    responsible: null,
    role: null,
    notes: null,
    work_plan: null,
    compensatory_controls: null,
    recategorization: null,
    estimated_budget: null,
    last_revision_date: '2024-10-29T21:39:08.154882Z',
    estimated_closure_date: null,
    closure_date: null,
    closure_reason: null,
    status: 'OPEN',
    evidence: null,
  },
];

mock.onGet(new RegExp('/api/data/vulnerabilities/management')).reply((config) => {
  try {
    const urlParams = new URLSearchParams(config.url!.split('?')[1]);

    const limit = 20;
    const page = parseInt(urlParams.get('page') || '1', 10); // Default to page 1

    const startIndex = (page - 1) * limit;
    const endIndex = startIndex + limit;

    const paginatedManagementVuln = managementVuln.slice(startIndex, endIndex);
    const totalManagementVulnerabilities = managementVuln.length;
    const totalPages = Math.ceil(totalManagementVulnerabilities / limit);

    return [
      200,
      {
        managedVuln: paginatedManagementVuln,
        currentPage: page,
        totalPages,
      },
    ];
  } catch (error) {
    console.error('Error in management vulnerabilities API:', error);
    return [500, { message: 'Internal server error' }];
  }
});

mock.onGet(new RegExp('/api/data/vulnerabilities/detail/management/*')).reply((config) => {
  try {
    const id = parseInt(config.url!.split('/').pop()!, 10);
    const vulnerability = managementVuln.find((vuln) => vuln.id === id);
    if (vulnerability) {
      return [200, vulnerability];
    } else {
      return [404, { message: 'Vulnerability not found' }];
    }
  } catch (error) {
    console.error('Error in vulnerability by ID API:', error);
    return [500, { message: 'Internal server error' }];
  }
});

mock.onPut(new RegExp('/api/data/vulnerabilities/form/management/*')).reply((config) => {
  try {
    const id = parseInt(config.url!.split('/').pop()!, 10);
    const vulnerability = managementVuln.find((vuln) => vuln.id === id);

    if (!vulnerability) {
      return [404, { message: 'Vulnerability not found' }];
    }

    const filledVulnerability = {
      ...vulnerability,
      responsible: vulnerability.responsible ?? null,
      role: vulnerability.role ?? null,
      notes: vulnerability.notes ?? null,
      work_plan: vulnerability.work_plan ?? null,
      compensatory_controls: vulnerability.compensatory_controls ?? null,
      recategorization: vulnerability.recategorization ?? null,
      estimated_budget: vulnerability.estimated_budget ?? 0,
      last_revision_date: vulnerability.last_revision_date ?? new Date().toISOString(),
      estimated_closure_date: vulnerability.estimated_closure_date ?? null,
      evidence: vulnerability.evidence ?? null,
    };

    return [200, { vulnerability: filledVulnerability }];
  } catch (error) {
    console.error('Error in processing vulnerability data:', error);
    return [500, { message: 'Failed to process vulnerability data' }];
  }
});
