// home/MalwareAnalysis.ts

import { EHReportType } from 'src/types/vulnerabilities/redteam/ethicalHackingReport';
import mock from '../../mock';


const ehReports: EHReportType[] = [
  {
    id: "1",
    name: "Informe Técnico EH - Octapus - Diciembre 2024",
    start_date_report: "01 diciembre 2024",
    end_date_report: "02 diciembre 2024",
    objectives: "1",
    created_date: new Date(),
    ehsummaries: {
      risk_exposure_level: 5,
      matriz_low_low: 8,
      matriz_low_medium: 4,
      matriz_low_high: 3,
      matriz_medium_low: 5,
      matriz_medium_medium: 7,
      matriz_medium_high: 1,
      matriz_high_low: 2,
      matriz_high_medium: 3,
      matriz_high_high: 0,
      comments: "Low risks with established controls.",
      description_tests: "Review of core security configurations.",
      first_conclusion: "Security standards are well-maintained.",
      second_conclusion: "No critical vulnerabilities found.",
      third_conclusion: "Regular audits are effective.",
      fourth_conclusion: "Access control is adequate.",
      fifth_conclusion: "Periodic monitoring is advised."
    },
    vulnerabilities: [
      {
        id: "1",
        idReport: "1",
        vulnerability: "SQL Injection",
        description: "Inyección de SQL en el parámetro de entrada",
        affected_components: "Base de datos",
        solution: "Validar y sanitizar entradas",
        identifier: "VULN-001",
        host: "192.168.1.1",
        port_protocol: "443/TCP",
        cvss_score: 7.5,
        risk: "High",
        impact: "High",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },
      {
        id: "2",
        idReport: "1",
        vulnerability: "Cross-Site Scripting",
        description: "XSS en campo de búsqueda",
        affected_components: "Frontend",
        solution: "Escape de caracteres especiales",
        identifier: "VULN-002",
        host: "192.168.1.2",
        port_protocol: "80/TCP",
        cvss_score: 6.1,
        risk: "Medium",
        impact: "Medium",
        probability_occurrence: "High",
        exploitable: true,
        created_date: new Date(),
      },
      {
        id: "3",
        idReport: "1",
        vulnerability: "Directory Traversal",
        description: "Acceso a archivos sensibles",
        affected_components: "Filesystem",
        solution: "Restringir acceso a directorios",
        identifier: "VULN-003",
        host: "192.168.1.3",
        port_protocol: "8080/TCP",
        cvss_score: 5.5,
        risk: "Medium",
        impact: "Medium",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },
      {
        id: "4",
        idReport: "1",
        vulnerability: "Remote Code Execution",
        description: "Ejecución remota de código a través de una vulnerabilidad en el servidor",
        affected_components: "Servidor",
        solution: "Actualizar el software del servidor",
        identifier: "VULN-004",
        host: "192.168.1.4",
        port_protocol: "22/TCP",
        cvss_score: 9.8,
        risk: "Critical",
        impact: "High",
        probability_occurrence: "High",
        exploitable: true,
        created_date: new Date(),
      },
      {
        id: "5",
        idReport: "1",
        vulnerability: "Insecure Deserialization",
        description: "Deserialización insegura que permite ataques de inyección",
        affected_components: "API",
        solution: "Validar y controlar la deserialización",
        identifier: "VULN-005",
        host: "192.168.1.5",
        port_protocol: "8443/TCP",
        cvss_score: 8.2,
        risk: "High",
        impact: "High",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },
      {
        id: "6",
        idReport: "1",
        vulnerability: "Misconfiguration",
        description: "Configuración insegura en el servidor web",
        affected_components: "Servidor web",
        solution: "Configurar adecuadamente los permisos",
        identifier: "VULN-006",
        host: "192.168.1.6",
        port_protocol: "80/TCP",
        cvss_score: 4.0,
        risk: "Low",
        impact: "Low",
        probability_occurrence: "Medium",
        exploitable: false,
        created_date: new Date(),
      },
      {
        id: "7",
        idReport: "1",
        vulnerability: "Information Disclosure",
        description: "Exposición de información sensible en encabezados HTTP",
        affected_components: "Headers",
        solution: "Configurar headers para ocultar información",
        identifier: "VULN-007",
        host: "192.168.1.7",
        port_protocol: "80/TCP",
        cvss_score: 3.1,
        risk: "Low",
        impact: "Low",
        probability_occurrence: "Low",
        exploitable: false,
        created_date: new Date(),
      },
      {
        id: "8",
        idReport: "1",
        vulnerability: "Broken Access Control",
        description: "Control de acceso deficiente que permite acceso no autorizado",
        affected_components: "Aplicación",
        solution: "Implementar control de acceso adecuado",
        identifier: "VULN-008",
        host: "192.168.1.8",
        port_protocol: "443/TCP",
        cvss_score: 7.8,
        risk: "High",
        impact: "High",
        probability_occurrence: "High",
        exploitable: true,
        created_date: new Date(),
      },
      {
        id: "9",
        idReport: "1",
        vulnerability: "Unvalidated Redirects and Forwards",
        description: "Redirecciones no validadas que permiten ataques de phishing",
        affected_components: "Enlaces",
        solution: "Validar URLs antes de redirigir",
        identifier: "VULN-009",
        host: "192.168.1.9",
        port_protocol: "443/TCP",
        cvss_score: 5.0,
        risk: "Medium",
        impact: "Medium",
        probability_occurrence: "Medium",
        exploitable: false,
        created_date: new Date(),
      },
      {
        id: "10",
        idReport: "1",
        vulnerability: "Cross-Site Request Forgery",
        description: "CSRF en solicitudes no autenticadas",
        affected_components: "Formulario de envío",
        solution: "Implementar tokens CSRF",
        identifier: "VULN-010",
        host: "192.168.1.10",
        port_protocol: "80/TCP",
        cvss_score: 6.2,
        risk: "Medium",
        impact: "Medium",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },
    ],
    evidences: [
      {
        file: "report_1.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-01",
      },
      {
        file: "screenshot_01.png",
        file_path: "https://innovationatwork.ieee.org/wp-content/uploads/2022/06/bigstock-Certified-Ethical-Hacker-Ceh-416158993_1024X684.png",
        created_date: "2024-11-02",
      },
      {
        file: "diagram_1.jpg",
        file_path: "https://focus.namirial.com/en/wp-content/uploads/sites/4/2022/10/ethical-hacker-1024x683.jpg",
        created_date: "2024-11-03",
      },
      {
        file: "report_2.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-04",
      },
      {
        file: "vulnerability_screenshot.png",
        file_path: "https://www.vpnmentor.com/wp-content/uploads/2024/06/4-autoresized86X.png",
        created_date: "2024-11-05",
      },
      {
        file: "report_summary.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-06",
      },
      {
        file: "network_map.jpg",
        file_path: "https://ars.els-cdn.com/content/image/1-s2.0-S2667345223000238-gr3.jpg",
        created_date: "2024-11-07",
      },
      {
        file: "error_details.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-08",
      },
      {
        file: "evidence_capture.png",
        file_path: "https://www.vpnmentor.com/wp-content/uploads/2024/06/6-autoresized86X.png",
        created_date: "2024-11-09",
      },
      {
        file: "final_report.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-10",
      },
    ]
  },
  {
    id: "2",
    name: "Informe Técnico EH - Octapus - Noviembre 2024",
    start_date_report: "01 noviembre 2024",
    end_date_report: "02 noviembre 2024",
    objectives: "2",
    created_date: new Date(),
    ehsummaries: {
      risk_exposure_level: 5,
      matriz_low_low: 8,
      matriz_low_medium: 4,
      matriz_low_high: 3,
      matriz_medium_low: 5,
      matriz_medium_medium: 7,
      matriz_medium_high: 1,
      matriz_high_low: 2,
      matriz_high_medium: 3,
      matriz_high_high: 0,
      comments: "Low risks with established controls.",
      description_tests: "Review of core security configurations.",
      first_conclusion: "Security standards are well-maintained.",
      second_conclusion: "No critical vulnerabilities found.",
      third_conclusion: "Regular audits are effective.",
      fourth_conclusion: "Access control is adequate.",
      fifth_conclusion: "Periodic monitoring is advised."
    },
    vulnerabilities: [
      {
        id: "1",
        idReport: "1",
        vulnerability: "SQL Injection",
        description: "Inyección de SQL en el parámetro de entrada",
        affected_components: "Base de datos",
        solution: "Validar y sanitizar entradas",
        identifier: "VULN-001",
        host: "192.168.1.1",
        port_protocol: "443/TCP",
        cvss_score: 7.5,
        risk: "High",
        impact: "High",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },
      {
        id: "2",
        idReport: "1",
        vulnerability: "Cross-Site Scripting",
        description: "XSS en campo de búsqueda",
        affected_components: "Frontend",
        solution: "Escape de caracteres especiales",
        identifier: "VULN-002",
        host: "192.168.1.2",
        port_protocol: "80/TCP",
        cvss_score: 6.1,
        risk: "Medium",
        impact: "Medium",
        probability_occurrence: "High",
        exploitable: true,
        created_date: new Date(),
      },
      {
        id: "3",
        idReport: "1",
        vulnerability: "Directory Traversal",
        description: "Acceso a archivos sensibles",
        affected_components: "Filesystem",
        solution: "Restringir acceso a directorios",
        identifier: "VULN-003",
        host: "192.168.1.3",
        port_protocol: "8080/TCP",
        cvss_score: 5.5,
        risk: "Medium",
        impact: "Medium",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },
      {
        id: "4",
        idReport: "1",
        vulnerability: "Remote Code Execution",
        description: "Ejecución remota de código a través de una vulnerabilidad en el servidor",
        affected_components: "Servidor",
        solution: "Actualizar el software del servidor",
        identifier: "VULN-004",
        host: "192.168.1.4",
        port_protocol: "22/TCP",
        cvss_score: 9.8,
        risk: "Critical",
        impact: "High",
        probability_occurrence: "High",
        exploitable: true,
        created_date: new Date(),
      },

      {
        id: "10",
        idReport: "1",
        vulnerability: "Cross-Site Request Forgery",
        description: "CSRF en solicitudes no autenticadas",
        affected_components: "Formulario de envío",
        solution: "Implementar tokens CSRF",
        identifier: "VULN-010",
        host: "192.168.1.10",
        port_protocol: "80/TCP",
        cvss_score: 6.2,
        risk: "Medium",
        impact: "Medium",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },
    ],
    evidences: [
      {
        file: "report_1.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-01",
      },
      {
        file: "screenshot_01.png",
        file_path: "https://innovationatwork.ieee.org/wp-content/uploads/2022/06/bigstock-Certified-Ethical-Hacker-Ceh-416158993_1024X684.png",
        created_date: "2024-11-02",
      },
      {
        file: "final_report.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-10",
      },
    ]
  },
  {
    id: "3",
    name: "Informe Técnico EH - Octapus - Octubre 2024",
    start_date_report: "01 octubre 2024",
    end_date_report: "02 octubre 2024",
    objectives: "3",
    created_date: new Date(),
    ehsummaries: {
      risk_exposure_level: 5,
      matriz_low_low: 8,
      matriz_low_medium: 4,
      matriz_low_high: 3,
      matriz_medium_low: 5,
      matriz_medium_medium: 7,
      matriz_medium_high: 1,
      matriz_high_low: 2,
      matriz_high_medium: 3,
      matriz_high_high: 0,
      comments: "Low risks with established controls.",
      description_tests: "Review of core security configurations.",
      first_conclusion: "Security standards are well-maintained.",
      second_conclusion: "No critical vulnerabilities found.",
      third_conclusion: "Regular audits are effective.",
      fourth_conclusion: "Access control is adequate.",
      fifth_conclusion: "Periodic monitoring is advised."
    },
    vulnerabilities: [
      {
        id: "6",
        idReport: "1",
        vulnerability: "Misconfiguration",
        description: "Configuración insegura en el servidor web",
        affected_components: "Servidor web",
        solution: "Configurar adecuadamente los permisos",
        identifier: "VULN-006",
        host: "192.168.1.6",
        port_protocol: "80/TCP",
        cvss_score: 4.0,
        risk: "Low",
        impact: "Low",
        probability_occurrence: "Medium",
        exploitable: false,
        created_date: new Date(),
      },
      {
        id: "7",
        idReport: "1",
        vulnerability: "Information Disclosure",
        description: "Exposición de información sensible en encabezados HTTP",
        affected_components: "Headers",
        solution: "Configurar headers para ocultar información",
        identifier: "VULN-007",
        host: "192.168.1.7",
        port_protocol: "80/TCP",
        cvss_score: 3.1,
        risk: "Low",
        impact: "Low",
        probability_occurrence: "Low",
        exploitable: false,
        created_date: new Date(),
      },
      {
        id: "8",
        idReport: "1",
        vulnerability: "Broken Access Control",
        description: "Control de acceso deficiente que permite acceso no autorizado",
        affected_components: "Aplicación",
        solution: "Implementar control de acceso adecuado",
        identifier: "VULN-008",
        host: "192.168.1.8",
        port_protocol: "443/TCP",
        cvss_score: 7.8,
        risk: "High",
        impact: "High",
        probability_occurrence: "High",
        exploitable: true,
        created_date: new Date(),
      },
      {
        id: "9",
        idReport: "1",
        vulnerability: "Unvalidated Redirects and Forwards",
        description: "Redirecciones no validadas que permiten ataques de phishing",
        affected_components: "Enlaces",
        solution: "Validar URLs antes de redirigir",
        identifier: "VULN-009",
        host: "192.168.1.9",
        port_protocol: "443/TCP",
        cvss_score: 5.0,
        risk: "Medium",
        impact: "Medium",
        probability_occurrence: "Medium",
        exploitable: false,
        created_date: new Date(),
      },
      {
        id: "10",
        idReport: "1",
        vulnerability: "Cross-Site Request Forgery",
        description: "CSRF en solicitudes no autenticadas",
        affected_components: "Formulario de envío",
        solution: "Implementar tokens CSRF",
        identifier: "VULN-010",
        host: "192.168.1.10",
        port_protocol: "80/TCP",
        cvss_score: 6.2,
        risk: "Medium",
        impact: "Medium",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },
    ],
    evidences: [
      {
        file: "report_1.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-01",
      },
      {
        file: "screenshot_01.png",
        file_path: "https://innovationatwork.ieee.org/wp-content/uploads/2022/06/bigstock-Certified-Ethical-Hacker-Ceh-416158993_1024X684.png",
        created_date: "2024-11-02",
      },
      {
        file: "diagram_1.jpg",
        file_path: "https://focus.namirial.com/en/wp-content/uploads/sites/4/2022/10/ethical-hacker-1024x683.jpg",
        created_date: "2024-11-03",
      },
      {
        file: "report_2.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-04",
      },
      {
        file: "vulnerability_screenshot.png",
        file_path: "https://www.vpnmentor.com/wp-content/uploads/2024/06/4-autoresized86X.png",
        created_date: "2024-11-05",
      },
    ]
  },
  {
    id: "4",
    name: "Informe Técnico EH - Octapus - Septiembre 2024",
    start_date_report: "01 septiembre 2024",
    end_date_report: "02 septiembre 2024",
    objectives: "1",
    created_date: new Date(),
    ehsummaries: {
      risk_exposure_level: 5,
      matriz_low_low: 8,
      matriz_low_medium: 4,
      matriz_low_high: 3,
      matriz_medium_low: 5,
      matriz_medium_medium: 7,
      matriz_medium_high: 1,
      matriz_high_low: 2,
      matriz_high_medium: 3,
      matriz_high_high: 0,
      comments: "Low risks with established controls.",
      description_tests: "Review of core security configurations.",
      first_conclusion: "Security standards are well-maintained.",
      second_conclusion: "No critical vulnerabilities found.",
      third_conclusion: "Regular audits are effective.",
      fourth_conclusion: "Access control is adequate.",
      fifth_conclusion: "Periodic monitoring is advised."
    },
    vulnerabilities: [
      {
        id: "1",
        idReport: "1",
        vulnerability: "SQL Injection",
        description: "Inyección de SQL en el parámetro de entrada",
        affected_components: "Base de datos",
        solution: "Validar y sanitizar entradas",
        identifier: "VULN-001",
        host: "192.168.1.1",
        port_protocol: "443/TCP",
        cvss_score: 7.5,
        risk: "High",
        impact: "High",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },
      {
        id: "4",
        idReport: "1",
        vulnerability: "Remote Code Execution",
        description: "Ejecución remota de código a través de una vulnerabilidad en el servidor",
        affected_components: "Servidor",
        solution: "Actualizar el software del servidor",
        identifier: "VULN-004",
        host: "192.168.1.4",
        port_protocol: "22/TCP",
        cvss_score: 9.8,
        risk: "Critical",
        impact: "High",
        probability_occurrence: "High",
        exploitable: true,
        created_date: new Date(),
      },
      {
        id: "5",
        idReport: "1",
        vulnerability: "Insecure Deserialization",
        description: "Deserialización insegura que permite ataques de inyección",
        affected_components: "API",
        solution: "Validar y controlar la deserialización",
        identifier: "VULN-005",
        host: "192.168.1.5",
        port_protocol: "8443/TCP",
        cvss_score: 8.2,
        risk: "High",
        impact: "High",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },
      {
        id: "6",
        idReport: "1",
        vulnerability: "Misconfiguration",
        description: "Configuración insegura en el servidor web",
        affected_components: "Servidor web",
        solution: "Configurar adecuadamente los permisos",
        identifier: "VULN-006",
        host: "192.168.1.6",
        port_protocol: "80/TCP",
        cvss_score: 4.0,
        risk: "Low",
        impact: "Low",
        probability_occurrence: "Medium",
        exploitable: false,
        created_date: new Date(),
      },
      {
        id: "9",
        idReport: "1",
        vulnerability: "Unvalidated Redirects and Forwards",
        description: "Redirecciones no validadas que permiten ataques de phishing",
        affected_components: "Enlaces",
        solution: "Validar URLs antes de redirigir",
        identifier: "VULN-009",
        host: "192.168.1.9",
        port_protocol: "443/TCP",
        cvss_score: 5.0,
        risk: "Medium",
        impact: "Medium",
        probability_occurrence: "Medium",
        exploitable: false,
        created_date: new Date(),
      },
      {
        id: "10",
        idReport: "1",
        vulnerability: "Cross-Site Request Forgery",
        description: "CSRF en solicitudes no autenticadas",
        affected_components: "Formulario de envío",
        solution: "Implementar tokens CSRF",
        identifier: "VULN-010",
        host: "192.168.1.10",
        port_protocol: "80/TCP",
        cvss_score: 6.2,
        risk: "Medium",
        impact: "Medium",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },
    ],
    evidences: [
      {
        file: "evidence_capture.png",
        file_path: "https://www.vpnmentor.com/wp-content/uploads/2024/06/6-autoresized86X.png",
        created_date: "2024-11-09",
      },
      {
        file: "final_report.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-10",
      },
    ]
  },
  {
    id: "5",
    name: "Informe Técnico EH - Octapus - Agosto 2024",
    start_date_report: "01 agosto 2024",
    end_date_report: "02 agosto 2024",
    objectives: "2",
    created_date: new Date(),
    ehsummaries: {
      risk_exposure_level: 5,
      matriz_low_low: 8,
      matriz_low_medium: 4,
      matriz_low_high: 3,
      matriz_medium_low: 5,
      matriz_medium_medium: 7,
      matriz_medium_high: 1,
      matriz_high_low: 2,
      matriz_high_medium: 3,
      matriz_high_high: 0,
      comments: "Low risks with established controls.",
      description_tests: "Review of core security configurations.",
      first_conclusion: "Security standards are well-maintained.",
      second_conclusion: "No critical vulnerabilities found.",
      third_conclusion: "Regular audits are effective.",
      fourth_conclusion: "Access control is adequate.",
      fifth_conclusion: "Periodic monitoring is advised."
    },
    vulnerabilities: [
      {
        id: "1",
        idReport: "1",
        vulnerability: "SQL Injection",
        description: "Inyección de SQL en el parámetro de entrada",
        affected_components: "Base de datos",
        solution: "Validar y sanitizar entradas",
        identifier: "VULN-001",
        host: "192.168.1.1",
        port_protocol: "443/TCP",
        cvss_score: 7.5,
        risk: "High",
        impact: "High",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },
      {
        id: "3",
        idReport: "1",
        vulnerability: "Directory Traversal",
        description: "Acceso a archivos sensibles",
        affected_components: "Filesystem",
        solution: "Restringir acceso a directorios",
        identifier: "VULN-003",
        host: "192.168.1.3",
        port_protocol: "8080/TCP",
        cvss_score: 5.5,
        risk: "Medium",
        impact: "Medium",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },
      {
        id: "4",
        idReport: "1",
        vulnerability: "Remote Code Execution",
        description: "Ejecución remota de código a través de una vulnerabilidad en el servidor",
        affected_components: "Servidor",
        solution: "Actualizar el software del servidor",
        identifier: "VULN-004",
        host: "192.168.1.4",
        port_protocol: "22/TCP",
        cvss_score: 9.8,
        risk: "Critical",
        impact: "High",
        probability_occurrence: "High",
        exploitable: true,
        created_date: new Date(),
      },
      {
        id: "6",
        idReport: "1",
        vulnerability: "Misconfiguration",
        description: "Configuración insegura en el servidor web",
        affected_components: "Servidor web",
        solution: "Configurar adecuadamente los permisos",
        identifier: "VULN-006",
        host: "192.168.1.6",
        port_protocol: "80/TCP",
        cvss_score: 4.0,
        risk: "Low",
        impact: "Low",
        probability_occurrence: "Medium",
        exploitable: false,
        created_date: new Date(),
      },
      {
        id: "7",
        idReport: "1",
        vulnerability: "Information Disclosure",
        description: "Exposición de información sensible en encabezados HTTP",
        affected_components: "Headers",
        solution: "Configurar headers para ocultar información",
        identifier: "VULN-007",
        host: "192.168.1.7",
        port_protocol: "80/TCP",
        cvss_score: 3.1,
        risk: "Low",
        impact: "Low",
        probability_occurrence: "Low",
        exploitable: false,
        created_date: new Date(),
      },
      {
        id: "9",
        idReport: "1",
        vulnerability: "Unvalidated Redirects and Forwards",
        description: "Redirecciones no validadas que permiten ataques de phishing",
        affected_components: "Enlaces",
        solution: "Validar URLs antes de redirigir",
        identifier: "VULN-009",
        host: "192.168.1.9",
        port_protocol: "443/TCP",
        cvss_score: 5.0,
        risk: "Medium",
        impact: "Medium",
        probability_occurrence: "Medium",
        exploitable: false,
        created_date: new Date(),
      },
    ],
    evidences: [
      {
        file: "report_1.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-01",
      },
      {
        file: "screenshot_01.png",
        file_path: "https://innovationatwork.ieee.org/wp-content/uploads/2022/06/bigstock-Certified-Ethical-Hacker-Ceh-416158993_1024X684.png",
        created_date: "2024-11-02",
      },
      {
        file: "diagram_1.jpg",
        file_path: "https://focus.namirial.com/en/wp-content/uploads/sites/4/2022/10/ethical-hacker-1024x683.jpg",
        created_date: "2024-11-03",
      },
      {
        file: "report_2.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-04",
      },
      {
        file: "final_report.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-10",
      },
    ]
  },
  {
    id: "6",
    name: "Informe Técnico EH - Octapus - Julio 2024",
    start_date_report: "01 julio 2024",
    end_date_report: "02 julio 2024",
    objectives: "3",
    created_date: new Date(),
    ehsummaries: {
      risk_exposure_level: 5,
      matriz_low_low: 8,
      matriz_low_medium: 4,
      matriz_low_high: 3,
      matriz_medium_low: 5,
      matriz_medium_medium: 7,
      matriz_medium_high: 1,
      matriz_high_low: 2,
      matriz_high_medium: 3,
      matriz_high_high: 0,
      comments: "Low risks with established controls.",
      description_tests: "Review of core security configurations.",
      first_conclusion: "Security standards are well-maintained.",
      second_conclusion: "No critical vulnerabilities found.",
      third_conclusion: "Regular audits are effective.",
      fourth_conclusion: "Access control is adequate.",
      fifth_conclusion: "Periodic monitoring is advised."
    },
    vulnerabilities: [
      {
        id: "1",
        idReport: "1",
        vulnerability: "SQL Injection",
        description: "Inyección de SQL en el parámetro de entrada",
        affected_components: "Base de datos",
        solution: "Validar y sanitizar entradas",
        identifier: "VULN-001",
        host: "192.168.1.1",
        port_protocol: "443/TCP",
        cvss_score: 7.5,
        risk: "High",
        impact: "High",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },

      {
        id: "10",
        idReport: "1",
        vulnerability: "Cross-Site Request Forgery",
        description: "CSRF en solicitudes no autenticadas",
        affected_components: "Formulario de envío",
        solution: "Implementar tokens CSRF",
        identifier: "VULN-010",
        host: "192.168.1.10",
        port_protocol: "80/TCP",
        cvss_score: 6.2,
        risk: "Medium",
        impact: "Medium",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },
    ],
    evidences: [
      {
        file: "report_1.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-01",
      },
    ]
  },
  {
    id: "7",
    name: "Informe Técnico EH - Octapus - Junio 2024",
    start_date_report: "01 junio 2024",
    end_date_report: "02 junio 2024",
    objectives: "1",
    created_date: new Date(),
    ehsummaries: {
      risk_exposure_level: 5,
      matriz_low_low: 8,
      matriz_low_medium: 4,
      matriz_low_high: 3,
      matriz_medium_low: 5,
      matriz_medium_medium: 7,
      matriz_medium_high: 1,
      matriz_high_low: 2,
      matriz_high_medium: 3,
      matriz_high_high: 0,
      comments: "Low risks with established controls.",
      description_tests: "Review of core security configurations.",
      first_conclusion: "Security standards are well-maintained.",
      second_conclusion: "No critical vulnerabilities found.",
      third_conclusion: "Regular audits are effective.",
      fourth_conclusion: "Access control is adequate.",
      fifth_conclusion: "Periodic monitoring is advised."
    },
    vulnerabilities: [
      {
        id: "1",
        idReport: "1",
        vulnerability: "SQL Injection",
        description: "Inyección de SQL en el parámetro de entrada",
        affected_components: "Base de datos",
        solution: "Validar y sanitizar entradas",
        identifier: "VULN-001",
        host: "192.168.1.1",
        port_protocol: "443/TCP",
        cvss_score: 7.5,
        risk: "High",
        impact: "High",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },
    ],
    evidences: [

      {
        file: "screenshot_01.png",
        file_path: "https://innovationatwork.ieee.org/wp-content/uploads/2022/06/bigstock-Certified-Ethical-Hacker-Ceh-416158993_1024X684.png",
        created_date: "2024-11-02",
      },
      {
        file: "diagram_1.jpg",
        file_path: "https://focus.namirial.com/en/wp-content/uploads/sites/4/2022/10/ethical-hacker-1024x683.jpg",
        created_date: "2024-11-03",
      },

      {
        file: "network_map.jpg",
        file_path: "https://ars.els-cdn.com/content/image/1-s2.0-S2667345223000238-gr3.jpg",
        created_date: "2024-11-07",
      },
    ]
  },
  {
    id: "8",
    name: "Informe Técnico EH - Octapus - Mayo 2024",
    start_date_report: "01 mayo 2024",
    end_date_report: "02 mayo 2024",
    objectives: "2",
    created_date: new Date(),
    ehsummaries: {
      risk_exposure_level: 5,
      matriz_low_low: 8,
      matriz_low_medium: 4,
      matriz_low_high: 3,
      matriz_medium_low: 5,
      matriz_medium_medium: 7,
      matriz_medium_high: 1,
      matriz_high_low: 2,
      matriz_high_medium: 3,
      matriz_high_high: 0,
      comments: "Low risks with established controls.",
      description_tests: "Review of core security configurations.",
      first_conclusion: "Security standards are well-maintained.",
      second_conclusion: "No critical vulnerabilities found.",
      third_conclusion: "Regular audits are effective.",
      fourth_conclusion: "Access control is adequate.",
      fifth_conclusion: "Periodic monitoring is advised."
    },
    vulnerabilities: [
      {
        id: "1",
        idReport: "1",
        vulnerability: "SQL Injection",
        description: "Inyección de SQL en el parámetro de entrada",
        affected_components: "Base de datos",
        solution: "Validar y sanitizar entradas",
        identifier: "VULN-001",
        host: "192.168.1.1",
        port_protocol: "443/TCP",
        cvss_score: 7.5,
        risk: "High",
        impact: "High",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },
      {
        id: "2",
        idReport: "1",
        vulnerability: "Cross-Site Scripting",
        description: "XSS en campo de búsqueda",
        affected_components: "Frontend",
        solution: "Escape de caracteres especiales",
        identifier: "VULN-002",
        host: "192.168.1.2",
        port_protocol: "80/TCP",
        cvss_score: 6.1,
        risk: "Medium",
        impact: "Medium",
        probability_occurrence: "High",
        exploitable: true,
        created_date: new Date(),
      },

      {
        id: "5",
        idReport: "1",
        vulnerability: "Insecure Deserialization",
        description: "Deserialización insegura que permite ataques de inyección",
        affected_components: "API",
        solution: "Validar y controlar la deserialización",
        identifier: "VULN-005",
        host: "192.168.1.5",
        port_protocol: "8443/TCP",
        cvss_score: 8.2,
        risk: "High",
        impact: "High",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },
      {
        id: "6",
        idReport: "1",
        vulnerability: "Misconfiguration",
        description: "Configuración insegura en el servidor web",
        affected_components: "Servidor web",
        solution: "Configurar adecuadamente los permisos",
        identifier: "VULN-006",
        host: "192.168.1.6",
        port_protocol: "80/TCP",
        cvss_score: 4.0,
        risk: "Low",
        impact: "Low",
        probability_occurrence: "Medium",
        exploitable: false,
        created_date: new Date(),
      },

      {
        id: "9",
        idReport: "1",
        vulnerability: "Unvalidated Redirects and Forwards",
        description: "Redirecciones no validadas que permiten ataques de phishing",
        affected_components: "Enlaces",
        solution: "Validar URLs antes de redirigir",
        identifier: "VULN-009",
        host: "192.168.1.9",
        port_protocol: "443/TCP",
        cvss_score: 5.0,
        risk: "Medium",
        impact: "Medium",
        probability_occurrence: "Medium",
        exploitable: false,
        created_date: new Date(),
      },
      {
        id: "10",
        idReport: "1",
        vulnerability: "Cross-Site Request Forgery",
        description: "CSRF en solicitudes no autenticadas",
        affected_components: "Formulario de envío",
        solution: "Implementar tokens CSRF",
        identifier: "VULN-010",
        host: "192.168.1.10",
        port_protocol: "80/TCP",
        cvss_score: 6.2,
        risk: "Medium",
        impact: "Medium",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },
    ],
    evidences: [
      {
        file: "report_1.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-01",
      },
      {
        file: "screenshot_01.png",
        file_path: "https://innovationatwork.ieee.org/wp-content/uploads/2022/06/bigstock-Certified-Ethical-Hacker-Ceh-416158993_1024X684.png",
        created_date: "2024-11-02",
      },
      {
        file: "diagram_1.jpg",
        file_path: "https://focus.namirial.com/en/wp-content/uploads/sites/4/2022/10/ethical-hacker-1024x683.jpg",
        created_date: "2024-11-03",
      },
      {
        file: "network_map.jpg",
        file_path: "https://ars.els-cdn.com/content/image/1-s2.0-S2667345223000238-gr3.jpg",
        created_date: "2024-11-07",
      },
      {
        file: "error_details.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-08",
      },
      {
        file: "evidence_capture.png",
        file_path: "https://www.vpnmentor.com/wp-content/uploads/2024/06/6-autoresized86X.png",
        created_date: "2024-11-09",
      },
      {
        file: "final_report.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-10",
      },
    ]
  },
  {
    id: "9",
    name: "Informe Técnico EH - Octapus - Abril 2024",
    start_date_report: "01 abril 2024",
    end_date_report: "02 abril 2024",
    objectives: "3",
    created_date: new Date(),
    ehsummaries: {
      risk_exposure_level: 5,
      matriz_low_low: 8,
      matriz_low_medium: 4,
      matriz_low_high: 3,
      matriz_medium_low: 5,
      matriz_medium_medium: 7,
      matriz_medium_high: 1,
      matriz_high_low: 2,
      matriz_high_medium: 3,
      matriz_high_high: 0,
      comments: "Low risks with established controls.",
      description_tests: "Review of core security configurations.",
      first_conclusion: "Security standards are well-maintained.",
      second_conclusion: "No critical vulnerabilities found.",
      third_conclusion: "Regular audits are effective.",
      fourth_conclusion: "Access control is adequate.",
      fifth_conclusion: "Periodic monitoring is advised."
    },
    vulnerabilities: [

      {
        id: "2",
        idReport: "1",
        vulnerability: "Cross-Site Scripting",
        description: "XSS en campo de búsqueda",
        affected_components: "Frontend",
        solution: "Escape de caracteres especiales",
        identifier: "VULN-002",
        host: "192.168.1.2",
        port_protocol: "80/TCP",
        cvss_score: 6.1,
        risk: "Medium",
        impact: "Medium",
        probability_occurrence: "High",
        exploitable: true,
        created_date: new Date(),
      },

    ],
    evidences: [
      {
        file: "report_1.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-01",
      },
      {
        file: "screenshot_01.png",
        file_path: "https://innovationatwork.ieee.org/wp-content/uploads/2022/06/bigstock-Certified-Ethical-Hacker-Ceh-416158993_1024X684.png",
        created_date: "2024-11-02",
      },
      {
        file: "diagram_1.jpg",
        file_path: "https://focus.namirial.com/en/wp-content/uploads/sites/4/2022/10/ethical-hacker-1024x683.jpg",
        created_date: "2024-11-03",
      },
      {
        file: "report_2.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-04",
      },
      {
        file: "evidence_capture.png",
        file_path: "https://www.vpnmentor.com/wp-content/uploads/2024/06/6-autoresized86X.png",
        created_date: "2024-11-09",
      },
      {
        file: "final_report.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-10",
      },
    ]
  },
  {
    id: "10",
    name: "Informe Técnico EH - Octapus - Marzo 2024",
    start_date_report: "01 marzo 2024",
    end_date_report: "02 marzo 2024",
    objectives: "1",
    created_date: new Date(),
    ehsummaries: {
      risk_exposure_level: 5,
      matriz_low_low: 8,
      matriz_low_medium: 4,
      matriz_low_high: 3,
      matriz_medium_low: 5,
      matriz_medium_medium: 7,
      matriz_medium_high: 1,
      matriz_high_low: 2,
      matriz_high_medium: 3,
      matriz_high_high: 0,
      comments: "Low risks with established controls.",
      description_tests: "Review of core security configurations.",
      first_conclusion: "Security standards are well-maintained.",
      second_conclusion: "No critical vulnerabilities found.",
      third_conclusion: "Regular audits are effective.",
      fourth_conclusion: "Access control is adequate.",
      fifth_conclusion: "Periodic monitoring is advised."
    },
    vulnerabilities: [
      {
        id: "1",
        idReport: "1",
        vulnerability: "SQL Injection",
        description: "Inyección de SQL en el parámetro de entrada",
        affected_components: "Base de datos",
        solution: "Validar y sanitizar entradas",
        identifier: "VULN-001",
        host: "192.168.1.1",
        port_protocol: "443/TCP",
        cvss_score: 7.5,
        risk: "High",
        impact: "High",
        probability_occurrence: "Medium",
        exploitable: true,
        created_date: new Date(),
      },
      {
        id: "2",
        idReport: "1",
        vulnerability: "Cross-Site Scripting",
        description: "XSS en campo de búsqueda",
        affected_components: "Frontend",
        solution: "Escape de caracteres especiales",
        identifier: "VULN-002",
        host: "192.168.1.2",
        port_protocol: "80/TCP",
        cvss_score: 6.1,
        risk: "Medium",
        impact: "Medium",
        probability_occurrence: "High",
        exploitable: true,
        created_date: new Date(),
      },

      {
        id: "6",
        idReport: "1",
        vulnerability: "Misconfiguration",
        description: "Configuración insegura en el servidor web",
        affected_components: "Servidor web",
        solution: "Configurar adecuadamente los permisos",
        identifier: "VULN-006",
        host: "192.168.1.6",
        port_protocol: "80/TCP",
        cvss_score: 4.0,
        risk: "Low",
        impact: "Low",
        probability_occurrence: "Medium",
        exploitable: false,
        created_date: new Date(),
      },
      {
        id: "7",
        idReport: "1",
        vulnerability: "Information Disclosure",
        description: "Exposición de información sensible en encabezados HTTP",
        affected_components: "Headers",
        solution: "Configurar headers para ocultar información",
        identifier: "VULN-007",
        host: "192.168.1.7",
        port_protocol: "80/TCP",
        cvss_score: 3.1,
        risk: "Low",
        impact: "Low",
        probability_occurrence: "Low",
        exploitable: false,
        created_date: new Date(),
      },
      {
        id: "8",
        idReport: "1",
        vulnerability: "Broken Access Control",
        description: "Control de acceso deficiente que permite acceso no autorizado",
        affected_components: "Aplicación",
        solution: "Implementar control de acceso adecuado",
        identifier: "VULN-008",
        host: "192.168.1.8",
        port_protocol: "443/TCP",
        cvss_score: 7.8,
        risk: "High",
        impact: "High",
        probability_occurrence: "High",
        exploitable: true,
        created_date: new Date(),
      },
    ],
    evidences: [
      {
        file: "report_1.pdf",
        file_path: "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
        created_date: "2024-11-01",
      },
      {
        file: "screenshot_01.png",
        file_path: "https://innovationatwork.ieee.org/wp-content/uploads/2022/06/bigstock-Certified-Ethical-Hacker-Ceh-416158993_1024X684.png",
        created_date: "2024-11-02",
      },
      {
        file: "diagram_1.jpg",
        file_path: "https://focus.namirial.com/en/wp-content/uploads/sites/4/2022/10/ethical-hacker-1024x683.jpg",
        created_date: "2024-11-03",
      },
    ]
  }
];

// GET: Fetch result mobile app by id
mock.onGet(new RegExp('/api/data/eh-reports/detail/*')).reply((config) => {
  try {
    const resultAppId = config.url!.split('/').pop();

    // Buscar el objeto que coincida con el id
    const ehReport = ehReports.find(ehReport => ehReport.id === resultAppId);

    if (!ehReport) {
      return [404, { message: 'ehReport not found' }];
    }

    return [
      200,
      {
        ehReport: ehReport
      },
    ];
  } catch (error) {
    console.error('Error in mobileApps API:', error);
    return [500, { message: 'Internal server error' }];
  }
});

// GET: Fetch paginated ehReports
mock.onGet(new RegExp('/api/data/eh-reports')).reply((config) => {
  try {
    const urlParams = new URLSearchParams(config.url!.split('?')[1]);

    const limit = 25;
    const page = parseInt(urlParams.get('page') || '1', 10); // Default to page 1

    const startIndex = (page - 1) * limit;
    const endIndex = startIndex + limit;

    const paginated = ehReports.slice(startIndex, endIndex);
    const total = ehReports.length;
    const totalPages = Math.ceil(total / limit);

    return [
      200,
      {
        ehReports: paginated,
        currentPage: page,
        totalPages,
      },
    ];
  } catch (error) {
    console.error('Error in ehReports API:', error);
    return [500, { message: 'Internal server error' }];
  }
});

// POST: Create a new ehReport
mock.onPost('/api/data/eh-reports').reply((config) => {
  try {
    const { start_date_report, end_date_report, objectives, created_date, ehsummaries, vulnerabilities, evidences } = JSON.parse(config.data);

    const newItem: EHReportType = {
      id: (ehReports.length + 1).toString(), // Simple id generation
      start_date_report, end_date_report, objectives, created_date, ehsummaries, vulnerabilities, evidences
    };

    ehReports.push(newItem);

    return [200, { ehReport: newItem }];
  } catch (error) {
    console.error('Error in creating Ethical Hacking Report:', error);
    return [500, { message: 'Failed to create Ethical Hacking Report' }];
  }
});

// PUT: Update an existing ehReport
mock.onPut(new RegExp('/api/data/eh-reports/*')).reply((config) => {
  try {
    const id = config.url!.split('/').pop(); // Extract the ehReport ID from the URL
    const updatedData = JSON.parse(config.data); // New data for the ehReport

    const index = ehReports.findIndex((ehReport) => ehReport.id === id);
    if (index === -1) {
      return [404, { message: 'Ethical Hacking Report not found' }];
    }

    ehReports[index] = { ...ehReports[index], ...updatedData }; // Update the ehReport

    return [200, { ehReport: ehReports[index] }];
  } catch (error) {
    console.error('Error updating Ethical Hacking Report:', error);
    return [500, { message: 'Failed to update Ethical Hacking Report' }];
  }
});

// DELETE: Delete an ehReport
mock.onDelete(new RegExp('/api/data/eh-reports/*')).reply((config) => {
  try {
    const id = config.url!.split('/').pop(); // Extract the ehReport ID from the URL

    const index = ehReports.findIndex((ehReport) => ehReport.id === id);
    if (index === -1) {
      return [404, { message: 'Ethical Hacking Report not found' }];
    }

    ehReports.splice(index, 1); // Remove ehReport from the mock database

    return [200, { message: 'Ethical Hacking Report deleted successfully' }];
  } catch (error) {
    console.error('Error deleting Ethical Hacking Report:', error);
    return [500, { message: 'Failed to delete Ethical Hacking Report' }];
  }
});
